# Generated by Django 5.0.3 on 2024-12-04 11:17

import pass_update_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type_id', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('last_updated', models.CharField(default=pass_update_register.models.code_generator, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AppleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_library_id', models.CharField(max_length=100)),
                ('push_token', models.CharField(max_length=300)),
                ('apple_pass', models.ManyToManyField(related_name='apple_device', to='pass_update_register.applepass')),
            ],
        ),
    ]
