# Generated by Django 5.0.3 on 2024-12-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_googleaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
    ]
