# Generated by Django 5.0.3 on 2025-01-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_googleaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
