# Generated by Django 5.0.3 on 2025-01-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueCatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField()),
                ('product_id', models.CharField(max_length=255)),
                ('period_type', models.CharField(max_length=50)),
                ('purchased_at', models.DateTimeField()),
                ('expiration_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.CharField(max_length=50)),
                ('entitlement_id', models.CharField(blank=True, max_length=255, null=True)),
                ('entitlement_ids', models.JSONField(default=list)),
                ('presented_offering_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('original_transaction_id', models.CharField(max_length=255)),
                ('is_family_share', models.BooleanField(default=False)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('app_user_id', models.CharField(max_length=255)),
                ('aliases', models.JSONField(default=list)),
                ('original_app_user_id', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_in_purchased_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscriber_attributes', models.JSONField(default=dict)),
                ('store', models.CharField(max_length=50)),
                ('takehome_percentage', models.FloatField(blank=True, null=True)),
                ('offer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255)),
                ('is_trial_conversion', models.BooleanField(blank=True, null=True)),
                ('expiration_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.FloatField(blank=True, null=True)),
                ('commission_percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
