# Generated by Django 5.0.3 on 2025-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_hooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuecatevent',
            name='entitlement_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='revenuecatevent',
            name='is_family_share',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='revenuecatevent',
            name='original_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='revenuecatevent',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
