# Generated by Django 5.0.3 on 2025-01-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_hooks', '0002_alter_revenuecatevent_entitlement_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuecatevent',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='revenuecatevent',
            name='price_in_purchased_currency',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
