# Generated by Django 5.0.3 on 2024-12-04 11:17

import django.db.models.deletion
import voucher_card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_user_profile', '0002_initial'),
        ('campaign', '0002_initial'),
        ('collector_card', '0001_initial'),
        ('customer_user_profile', '0001_initial'),
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateField(blank=True, null=True)),
                ('date_used', models.DateTimeField(auto_now=True)),
                ('is_used', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(upload_to=voucher_card.models.voucher_qr_directory_path)),
                ('serial_nr', models.CharField(default=voucher_card.models.code_generator, max_length=15, unique=True)),
                ('business_id', models.IntegerField(blank=True, null=True, verbose_name='business id')),
                ('to_qr', models.CharField(max_length=400, verbose_name='jwt{voucher_id, secret_key}')),
                ('business_user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='business_user_profile.businessuserprofile')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_card', to='campaign.campaign')),
                ('collector_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_cards', to='collector_card.collectorcard')),
                ('customer_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_user_profile.customeruserprofile')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_card', to='promotion.promotion')),
                ('voucher_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher_cards', to='voucher_card.vouchertype')),
            ],
        ),
    ]
