# Generated by Django 5.0.3 on 2024-12-04 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_user_profile', '0002_initial'),
        ('campaign', '0002_initial'),
        ('collector_card', '0002_initial'),
        ('customer_user_profile', '0001_initial'),
        ('model_logs', '0001_initial'),
        ('promotion', '0002_initial'),
        ('voucher_card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logscampaign',
            name='business_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_campaign', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='logscampaign',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='logscollectorcard',
            name='collector_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='collector_card.collectorcard'),
        ),
        migrations.AddField(
            model_name='logscollectorcard',
            name='customer_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_collector_card', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='logsfollowbusiness',
            name='business_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_logs', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='logsfollowbusiness',
            name='customer_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_follow_business', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='logspromotion',
            name='business_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_promotion', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='logspromotion',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='promotion.promotion'),
        ),
        migrations.AddField(
            model_name='logssubscribebusiness',
            name='business_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='logssubscribebusiness',
            name='customer_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_subscription_business', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='logsteamsrequest',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsteamsrequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsvouchercard',
            name='customer_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_voucher_card', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='logsvouchercard',
            name='voucher_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='voucher_card.vouchercard'),
        ),
        migrations.AddField(
            model_name='logswallmessage',
            name='business_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_wall_message', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='logswallmessage',
            name='customer_user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_wall_message', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='logswallmessage',
            name='wall_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_logs', to='business_user_profile.businesswallmessage'),
        ),
    ]
