# Generated by Django 5.0.3 on 2024-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_logs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsvouchercard',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
