version: '3'
services:
  backend:
    image: registry.gitlab.com/ugem.app/ugem:latest
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    command: 'tail -f /dev/null'
    env_file:
      - envs/dev.env
    depends_on:
      - database
      - redis
  database:
    image: postgres:16
    ports:
      - 5556:5432
    env_file:
      - envs/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7.4.1
    ports:
      - 6379:6379
    env_file:
      - envs/dev.env

volumes:
  postgres_data:
