# Generated by Django 5.0.3 on 2024-12-04 11:17

import collector_card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectorCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_added', models.FloatField(default=0)),
                ('value_counted', models.FloatField(default=0)),
                ('value_goal', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateField(blank=True, null=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
                ('to_qr', models.CharField(max_length=400, verbose_name='jwt{voucher_id, secret_key}')),
                ('serial_nr', models.CharField(default=collector_card.models.code_generator, max_length=15, unique=True, verbose_name='Serial nr')),
                ('qr_code', models.ImageField(blank=True, upload_to=collector_card.models.collector_card_qr_path, verbose_name='Customers QR code')),
            ],
        ),
        migrations.CreateModel(
            name='LogsCollector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_id_nr', models.IntegerField(blank=True, null=True)),
                ('value_added', models.FloatField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
