# Generated by Django 5.0.3 on 2024-12-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_user_profile', '0002_initial'),
        ('campaign', '0002_initial'),
        ('collector_card', '0001_initial'),
        ('customer_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorcard',
            name='business_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='collectorcard',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectors', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='collectorcard',
            name='customer_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectors', to='customer_user_profile.customeruserprofile'),
        ),
        migrations.AddField(
            model_name='logscollector',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_collectors', to='collector_card.collectorcard'),
        ),
    ]
