# Generated by Django 5.0.3 on 2024-12-04 11:17

import customer_user_profile.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_user_profile', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUserProfile',
            fields=[
                ('code', models.CharField(default=customer_user_profile.models.code_generator, max_length=15, unique=True)),
                ('secret_key', models.CharField(default=customer_user_profile.models.code_generator, max_length=15, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=80, verbose_name='last name')),
                ('country', models.CharField(blank=True, max_length=80, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='city')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='street')),
                ('street_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='street number')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='zip')),
                ('avatar', models.ImageField(blank=True, upload_to=customer_user_profile.models.avatar_directory_path, verbose_name='avatar')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('followed_businesses', models.ManyToManyField(blank=True, related_name='followers', to='business_user_profile.businessuserprofile')),
                ('liked_messages', models.ManyToManyField(blank=True, related_name='likes', to='business_user_profile.businesswallmessage')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='customer_user_profile.customeruserprofile')),
                ('referred_by_business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='business_user_profile.businessuserprofile')),
                ('subscribed_businesses', models.ManyToManyField(blank=True, related_name='subscribers', to='business_user_profile.businessuserprofile')),
            ],
        ),
    ]
