# Generated by Django 5.0.3 on 2024-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruserprofile',
            name='agreed_tos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customeruserprofile',
            name='agreed_tos_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
