# Generated by Django 5.0.3 on 2024-12-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_profile', '0002_customeruserprofile_agreed_tos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruserprofile',
            name='agreed_tos_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
