# Generated by Django 5.0.3 on 2025-02-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user_profile', '0004_customeruserprofile_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruserprofile',
            name='device_id',
        ),
    ]
