# Generating a file with 1000 adjectives

adj_list = [
    "Able", "Abundant", "Accepting", "Accomplished", "Accurate", "Active", "Adaptable", "Adventurous",
    "Affectionate", "Agile", "Agreeable", "Alert", "Alive", "Alluring", "Altruistic", "Amazing", "Ambitious",
    "Ample", "Amusing", "Angelic", "Appealing", "Appreciative", "Artistic", "Assertive", "Astonishing",
    "Attentive", "Attractive", "Authentic", "Aware", "Awesome", "Balanced", "Beautiful", "Beloved",
    "Benevolent", "Big-hearted", "Blissful", "Bold", "Brave", "Bright", "Brilliant", "Bubbly", "Buoyant",
    "Calm", "Capable", "Carefree", "Caring", "Charismatic", "Charming", "Cheerful", "Chic", "Chivalrous",
    "Classy", "Clever", "Colorful", "Comfortable", "Compassionate", "Confident", "Considerate", "Content",
    "Cool", "Cooperative", "Courageous", "Creative", "Crisp", "Cultured", "Curious", "Dainty", "Daring",
    "Dashing", "Dazzling", "Debonair", "Decisive", "Dedicated", "Delightful", "Dependable", "Desirable",
    "Determined", "Devoted", "Dignified", "Diligent", "Diplomatic", "Discerning", "Distinct", "Divine",
    "Dominant", "Dramatic", "Dreamy", "Dynamic", "Eager", "Earnest", "Easygoing", "Ebullient", "Eclectic",
    "Ecstatic", "Educated", "Eloquent", "Empathetic", "Enchanting", "Encouraging", "Endearing", "Energetic",
    "Engaging", "Enigmatic", "Enterprising", "Enthusiastic", "Ethereal", "Euphoric", "Excellent", "Exemplary",
    "Exotic", "Expansive", "Experienced", "Extraordinary", "Exuberant", "Fabulous", "Fair", "Faithful",
    "Fanciful", "Fantastic", "Fearless", "Feisty", "Fertile", "Fervent", "Festive", "Fiery", "Fine", "Flamboyant",
    "Flawless", "Flexible", "Flourishing", "Focused", "Fond", "Forbearing", "Forgiving", "Forthright", "Fortunate",
    "Free-spirited", "Friendly", "Frolicsome", "Fruitful", "Fulfilled", "Fun-loving", "Funny", "Gallant", "Generous",
    "Genial", "Genuine", "Gifted", "Glamorous", "Gleeful", "Glorious", "Golden", "Good-natured", "Graceful",
    "Gracious", "Grand", "Grateful", "Great", "Gregarious", "Groovy", "Grounded", "Handsome", "Hardworking",
    "Harmonious", "Healthy", "Heartfelt", "Heartwarming", "Helpful", "Heroic", "High-spirited", "Honest",
    "Honorable", "Hopeful", "Hospitable", "Humble", "Humorous", "Idealistic", "Imaginative", "Immaculate",
    "Impartial", "Impressive", "Industrious", "Influential", "Ingenious", "Innovative", "Inspiring", "Intelligent",
    "Intuitive", "Inventive", "Invigorating", "Joyful", "Jubilant", "Judicious", "Kaleidoscopic", "Keen", "Kind",
    "Knowledgeable", "Lively", "Logical", "Lovable", "Loyal", "Lucky", "Luminous", "Lush", "Luxurious", "Magnetic",
    "Magnificent", "Majestic", "Marvelous", "Mature", "Meticulous", "Mindful", "Modest", "Motivated", "Mysterious",
    "Natural", "Neat", "Noble", "Nurturing", "Optimistic", "Opulent", "Outstanding", "Passionate", "Patient",
    "Peaceful", "Perceptive", "Persevering", "Persistent", "Personable", "Persuasive", "Philanthropic",
    "Picturesque", "Playful", "Pleasant", "Poised", "Polished", "Popular", "Positive", "Powerful", "Practical",
    "Precise", "Prestigious", "Proactive", "Productive", "Progressive", "Prominent", "Prosperous", "Proud",
    "Punctual", "Quaint", "Quick-witted", "Radiant", "Rational", "Realistic", "Receptive", "Refined", "Relaxed",
    "Reliable", "Remarkable", "Resilient", "Resolute", "Resourceful", "Respectful", "Responsible", "Reverent",
    "Rich", "Romantic", "Sacred", "Safe", "Sage", "Satisfying", "Savvy", "Scenic", "Scholarly", "Secure",
    "Self-assured", "Selfless", "Sensitive", "Serene", "Sharp", "Shining", "Shrewd", "Simple", "Sincere",
    "Skilled", "Smart", "Sociable", "Sophisticated", "Soulful", "Sparkling", "Spirited", "Splendid", "Stable",
    "Steadfast", "Stimulating", "Strong", "Stunning", "Suave", "Successful", "Sunny", "Superb", "Supportive",
    "Surprising", "Sweet", "Sympathetic", "Talented", "Tasteful", "Tactful", "Tangible", "Teachable", "Tenacious",
    "Terrific", "Thankful", "Thoughtful", "Thrilling", "Tidy", "Tolerant", "Tough", "Tranquil", "Trustworthy",
    "Unassuming", "Unbreakable", "Understanding", "Unique", "Uplifting", "Valiant", "Vibrant", "Vigilant",
    "Virtuous", "Vivacious", "Warm", "Witty", "Wise", "Wonderful", "Youthful", "Zealous", "Zesty", "Zippy"
]
