noun_list = [
    "Tiger", "Eagle", "Panther", "Wizard", "Knight", "Fox", "Hawk", "Shadow", "Falcon", "Wolf",
    "Lion", "Dragon", "Phoenix", "Jaguar", "Samurai", "Ninja", "Warrior", "Ranger", "Sentinel", "Gladiator",
    "Champion", "Sorcerer", "Alchemist", "Scholar", "Guardian", "Seeker", "Voyager", "Explorer", "Pirate", "Captain",
    "Commander", "Sage", "Mystic", "Nomad", "Rogue", "Assassin", "Magician", "Shaman", "Prophet", "Oracle",
    "Hunter", "Archer", "Swordsman", "Druid", "Healer", "Monk", "Paladin", "Berserker", "Viking", "Mercenary",
    "Inventor", "Engineer", "Scientist", "Professor", "Tinker", "Adventurer", "Traveler", "Wanderer", "Pioneer",
    "Gambler", "Trickster", "Illusionist", "Jester", "Enchanter", "Bard", "Minstrel", "Poet", "Artist", "Painter",
    "Sculptor", "Writer", "Storyteller", "Scribe", "Craftsman", "Smith", "Tailor", "Carpenter", "Architect", "Builder",
    "Pilot", "Astronaut", "Cosmonaut", "Spaceman", "Navigator", "Sailor", "Fisherman", "Mariner", "Diver", "Explorer",
    "Survivor", "Rescuer", "Hero", "Legend", "Icon", "Symbol", "Monument", "Beacon", "Light", "Torch",
    "Flame", "Ember", "Inferno", "Storm", "Blizzard", "Hurricane", "Tornado", "Cyclone", "Earthquake", "Avalanche",
    "Tsunami", "Wave", "Current", "Tide", "River", "Stream", "Waterfall", "Spring", "Lake", "Ocean",
    "Sea", "Bay", "Harbor", "Island", "Peninsula", "Mountain", "Peak", "Summit", "Cliff", "Canyon",
    "Valley", "Plateau", "Desert", "Oasis", "Forest", "Jungle", "Woods", "Grove", "Field", "Meadow",
    "Prairie", "Savanna", "Tundra", "Glacier", "Cavern", "Cave", "Tunnel", "Chasm", "Abyss", "Void",
    "Star", "Planet", "Galaxy", "Nebula", "Meteor", "Comet", "Asteroid", "Satellite", "Orbit", "Cosmos",
    "Storm", "Thunder", "Lightning", "Rain", "Hail", "Snow", "Mist", "Fog", "Dew", "Frost",
    "Breeze", "Gale", "Zephyr", "Whirlwind", "Sun", "Moon", "Eclipse", "Twilight", "Dawn", "Dusk",
    "Night", "Day", "Eon", "Era", "Epoch", "Century", "Decade", "Year", "Season", "Solstice",
    "Equinox", "Shadow", "Light", "Glow", "Radiance", "Aura", "Horizon", "Echo", "Mirage", "Illusion",
    "Phantom", "Spirit", "Soul", "Entity", "Wraith", "Specter", "Ghost", "Apparition", "Shade", "Poltergeist",
    "Charm", "Spell", "Incantation", "Curse", "Blessing", "Ritual", "Totem", "Talisman", "Amulet", "Relic",
    "Artifact", "Treasure", "Gem", "Jewel", "Crystal", "Pearl", "Emerald", "Ruby", "Sapphire", "Diamond",
    "Gold", "Silver", "Bronze", "Platinum", "Coin", "Medallion", "Crown", "Scepter", "Throne", "Castle",
    "Palace", "Fortress", "Tower", "Citadel", "Stronghold", "Keep", "Dungeon", "Labyrinth", "Maze", "Cavern",
    "Crypt", "Tomb", "Grave", "Shrine", "Temple", "Monastery", "Sanctuary", "Altar", "Chapel", "Church",
    "Cathedral", "Mosque", "Synagogue", "Pagoda", "Monument", "Obelisk", "Statue", "Bust", "Colossus", "Pyramid",
]
