# Generated by Django 5.0.3 on 2024-12-04 11:17

import business_user_profile.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_user_profile', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('code', models.CharField(default=business_user_profile.models.code_generator, max_length=15, unique=True)),
                ('business_name', models.CharField(max_length=100, verbose_name='business name')),
                ('about', models.TextField(blank=True, default='Hello :)', max_length=1000, null=True, verbose_name='about')),
                ('country', models.CharField(max_length=80, verbose_name='country')),
                ('city', models.CharField(max_length=60, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('street_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='street number')),
                ('zip', models.CharField(max_length=10, verbose_name='zip')),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='longitude')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=business_user_profile.models.logo_directory_path, verbose_name='logo')),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to=business_user_profile.models.shop_image_directory_path, verbose_name='shop_image')),
                ('qr_code', models.ImageField(upload_to=business_user_profile.models.business_user_qr_directory_path)),
                ('is_verified', models.BooleanField(blank=True, default=False, null=True)),
                ('business_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='business_user_profile.businesscategory')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessWallMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=300, verbose_name='Message on wall')),
                ('business_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_wall', to='business_user_profile.businessuserprofile')),
            ],
        ),
    ]
