# Generated by Django 5.0.3 on 2024-12-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_user_profile', '0004_googleaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
    ]
