# Generated by Django 5.0.3 on 2025-01-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_user_profile', '0007_alter_businessuserprofile_agreed_tos_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuserprofile',
            name='subscription',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
