# Generated by Django 5.0.3 on 2025-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_user_profile', '0008_businessuserprofile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessuserprofile',
            name='is_vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
