# Generated by Django 5.0.3 on 2024-12-04 11:17

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True, verbose_name='campaign description')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='additional information')),
                ('value_goal', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('beginning_date', models.DateField(auto_now_add=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to=campaign.models.campaign_directory_path, verbose_name='image')),
                ('logo', models.ImageField(blank=True, upload_to=campaign.models.campaign_directory_path, verbose_name='logo')),
            ],
        ),
        migrations.CreateModel(
            name='CollectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StampDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
