# Generated by Django 5.0.3 on 2024-12-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_user_profile', '0002_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='business_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='business_user_profile.businessuserprofile'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='collector_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.collectortype'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='stamp_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaigns', to='campaign.stampdesign'),
        ),
    ]
