# Generated by Django 5.0.3 on 2025-02-06 07:50

import campaign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_create_initial_stamp_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=campaign.models.campaign_directory_path, verbose_name='QR code'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='secret_key',
            field=models.CharField(blank=True, default=campaign.models.code_generator, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='self_scann_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of points or stamps gets when scan'),
        ),
    ]
