# Generated by Django 5.0.3 on 2025-02-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaign_qr_code_campaign_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='color',
            field=models.CharField(default='#6870ec', max_length=20),
        ),
    ]
