# Generated by Django 5.0.3 on 2024-12-04 11:17

import promotion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(verbose_name='promotion description')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='additional information')),
                ('image', models.ImageField(blank=True, null=True, upload_to=promotion.models.deal_directory_path, verbose_name='promotion image')),
                ('vouchers_amount', models.IntegerField(verbose_name='amount of vouchers')),
                ('vouchers_issued', models.IntegerField(default=0, verbose_name='amount of vouchers issued')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_ends', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='is active')),
            ],
        ),
    ]
