# Generated by Django 5.0.3 on 2024-12-04 11:17

import customer_card.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, upload_to=customer_card.models.customer_card_thumbnail_directory_path)),
                ('to_qr', models.CharField(max_length=400, verbose_name='jwt{secret_key}')),
                ('serial_nr', models.CharField(default=customer_card.models.code_generator, max_length=15, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to=customer_card.models.customer_card_qr_directory_path)),
                ('card_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_card_type', to='customer_card.cardtype')),
            ],
        ),
    ]
