# Generated by Django 5.0.3 on 2024-12-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_card', '0001_initial'),
        ('customer_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='customer_user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_card', to='customer_user_profile.customeruserprofile'),
        ),
    ]
